// Generated by gencpp from file xx_msgs/Flag_xx.msg
// DO NOT EDIT!


#ifndef XX_MSGS_MESSAGE_FLAG_XX_H
#define XX_MSGS_MESSAGE_FLAG_XX_H

#include <ros/service_traits.h>


#include <xx_msgs/Flag_xxRequest.h>
#include <xx_msgs/Flag_xxResponse.h>


namespace xx_msgs
{

struct Flag_xx
{

typedef Flag_xxRequest Request;
typedef Flag_xxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Flag_xx
} // namespace xx_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xx_msgs::Flag_xx > {
  static const char* value()
  {
    return "30f07fd1b48dfe19e8223bd0e3a0cdf5";
  }

  static const char* value(const ::xx_msgs::Flag_xx&) { return value(); }
};

template<>
struct DataType< ::xx_msgs::Flag_xx > {
  static const char* value()
  {
    return "xx_msgs/Flag_xx";
  }

  static const char* value(const ::xx_msgs::Flag_xx&) { return value(); }
};


// service_traits::MD5Sum< ::xx_msgs::Flag_xxRequest> should match 
// service_traits::MD5Sum< ::xx_msgs::Flag_xx > 
template<>
struct MD5Sum< ::xx_msgs::Flag_xxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xx_msgs::Flag_xx >::value();
  }
  static const char* value(const ::xx_msgs::Flag_xxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xx_msgs::Flag_xxRequest> should match 
// service_traits::DataType< ::xx_msgs::Flag_xx > 
template<>
struct DataType< ::xx_msgs::Flag_xxRequest>
{
  static const char* value()
  {
    return DataType< ::xx_msgs::Flag_xx >::value();
  }
  static const char* value(const ::xx_msgs::Flag_xxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xx_msgs::Flag_xxResponse> should match 
// service_traits::MD5Sum< ::xx_msgs::Flag_xx > 
template<>
struct MD5Sum< ::xx_msgs::Flag_xxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xx_msgs::Flag_xx >::value();
  }
  static const char* value(const ::xx_msgs::Flag_xxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xx_msgs::Flag_xxResponse> should match 
// service_traits::DataType< ::xx_msgs::Flag_xx > 
template<>
struct DataType< ::xx_msgs::Flag_xxResponse>
{
  static const char* value()
  {
    return DataType< ::xx_msgs::Flag_xx >::value();
  }
  static const char* value(const ::xx_msgs::Flag_xxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XX_MSGS_MESSAGE_FLAG_XX_H
